eslint:
  enabled: true
  config_file: .eslintrc.json

ruby:
  enabled: false

coffeescript:
  enabled: false

jshint:
  enabled: false

scss:
  enabled: false

haml:
  enabled: false

swift:
  enabled: false

python:
  enabled: false

tslint:
  enabled: false

elixir:
  enabled: false
